DROP DATABASE IF EXISTS DBMS;
CREATE DATABASE IF NOT EXISTS DBMS;
USE DBMS;

-- Question 1

CREATE TABLE EMP (
    EMPNO INT(6),
    EFNAME VARCHAR(20),
    ELNAME VARCHAR(20),
    JOB VARCHAR(10),
    DEPTNAME VARCHAR(10),
    DEPTNO INT(2),
    ECITY VARCHAR(10),
    SAL NUMERIC(9,2),
    WORKEXPERIENCE INT(10),
    MANAGERNAME VARCHAR(10),
    MANAGERNO INT(20)
);

CREATE TABLE dept (
    DEPTNO INT(2),
    DNAME VARCHAR(10),
    LOC VARCHAR(10),
    LOCID INT(5)
);

DESC EMP;
DESC dept;

INSERT INTO EMP (EMPNO, EFNAME, ELNAME, JOB, DEPTNAME, DEPTNO, ECITY, SAL, WORKEXPERIENCE, MANAGERNAME, MANAGERNO)
VALUES
(1, 'John', 'Doe', 'Manager', 'HR', 10, 'New York', 5000.00, 5, 'Jane', 100),
(2, 'Alice', 'Smith', 'Analyst', 'Finance', 20, 'London', 4000.00, 3, 'Sam', 105),
(3, 'Bob', 'Johnson', 'Analyst', 'Finance', 20, 'London', 4000.00, 3, 'Sam', 105),
(4, 'Jane', 'Doe', 'Analyst', 'Finance', 20, 'London', 4000.00, 3, 'Sam', 105),
(5, 'Sam', 'Smith', 'Analyst', 'Finance', 20, 'London', 4000.00, 3, 'Sam', 105);

INSERT INTO dept (DEPTNO, DNAME, LOC, LOCID) VALUES
(10, 'HR', 'New York', 1),
(20, 'Finance', 'London', 2),
(30, 'IT', 'New York', 1),
(40, 'Sales', 'London', 2),
(50, 'Marketing', 'New York', 1);

SELECT * FROM EMP;
SELECT * FROM dept;

SELECT ELNAME, DEPTNO, DEPTNAME FROM EMP;

SELECT JOB, dept.LOCID
FROM EMP, dept
WHERE DEPTNAME = 'Finance'
GROUP BY JOB, dept.LOCID;

SELECT EMP.ELNAME, EMP.DEPTNAME, dept.LOCID, dept.LOC
FROM EMP, dept
WHERE EMP.DEPTNO = dept.DEPTNO AND EMP.SAL > 0;

SELECT ELNAME, DEPTNAME
FROM EMP
WHERE ELNAME LIKE '%o%';

SELECT ELNAME, EMPNO, MANAGERNO, MANAGERNAME
FROM EMP
WHERE EMPNO NOT IN (SELECT MANAGERNO FROM EMP);


SELECT e.ELNAME, e.JOB, e.DEPTNO, e.DEPTNAME
FROM EMP e
WHERE e.ECITY = 'London' AND e.JOB = 'Analyst';


SELECT ELNAME, EMPNO, MANAGERNO, MANAGERNAME
FROM EMP
WHERE EMPNO NOT IN (SELECT MANAGERNO FROM EMP) OR EFNAME = "Sam";

SELECT ELNAME, DEPTNO from EMP where DEPTNAME = (
    SELECT DEPTNAME
    FROM EMP
    WHERE ELNAME = 'Sam'
);

select sum(sal), avg(sal) from EMP;

SELECT * FROM EMP
WHERE WORKEXPERIENCE = (
    SELECT MAX(WORKEXPERIENCE) 
    FROM EMP
);

SELECT COUNT(EMPNO) as COUNT_EMP FROM EMP;

SELECT * FROM EMP
WHERE WORKEXPERIENCE = (
    SELECT MIN(WORKEXPERIENCE) 
    FROM EMP
);


SELECT * FROM EMP
WHERE SAL = (
    SELECT MAX(SAL) 
    FROM EMP
);


-- Qustion 2

CREATE TABLE Depositor (
    CUSNAME VARCHAR(20),
    ACC_NO VARCHAR(20),
    PRIMARY KEY (CUSNAME, ACC_NO)
);

INSERT INTO Depositor (CUSNAME, ACC_NO) VALUES
('John', '12345'),
('Alice', '67890'),
('Bob', '54321'),
('Emma', '98765'),
('Charlie', '13579');

CREATE TABLE Borrower (
    CUSNAME VARCHAR(20),
    LOAN_NO VARCHAR(20),
    PRIMARY KEY (CUSNAME, LOAN_NO)
);

INSERT INTO Borrower (CUSNAME, LOAN_NO) VALUES
('John', 'LN001'),
('Alice', 'LN002'),
('Emma', 'LN003'),
('David', 'LN004'),
('Alice', 'LN005');


SELECT CUSNAME FROM Depositor
UNION
SELECT CUSNAME FROM Borrower;

SELECT CUSNAME FROM Depositor
INTERSECT
SELECT CUSNAME FROM Borrower;

SELECT CUSNAME FROM Borrower
EXCEPT
SELECT CUSNAME FROM Depositor;
