DROP DATABASE IF EXISTS DBMS;
CREATE DATABASE IF NOT EXISTS DBMS;
USE DBMS;

CREATE TABLE EMP (
    EMPLOYEE_ID INT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE,
    JOB_ID VARCHAR(20),
    COMMISSION_PCT FLOAT,
    MANAGER_ID INT,
    DEPARTMENT_ID INT
);

CREATE TABLE DEPT (
    DEPARTMENT_ID INT,
    DEPARTMENT_NAME VARCHAR(50),
    MANAGER_ID INT,
    LOCATION_ID INT
);

CREATE TABLE LOCA (
    LOCATION_ID INT,
    STREET_ADDRESS VARCHAR(100),
    POSTAL_CODE INT,
    CITY VARCHAR(50),
    STATE_PROVINCE VARCHAR(50),
    COUNTRY_ID INT
);

INSERT INTO EMP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES
(134, 'John', 'Doe', 'john@example.com', '123-456-7890', '2023-01-01', 'IT_PROG', 0.1, 100, 10),
(122, 'Alice', 'Smith', 'alice@example.com', '987-654-3210', '2023-02-01', 'AD_VP', 0.15, 101, 20),
(159, 'William', 'Miller', 'william@example.com', '123-456-7890', '2023-06-25', 'FI_ACCOUNT', 0.11, 103, 40),
(105, 'Olivia', 'Davis', 'olivia@example.com', '987-654-3210', '2023-07-30', 'PR_REP', 0.14, 204, 70);


INSERT INTO DEPT (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES
(30, 'Purchasing', 100, 3),
(40, 'Finance', 101, 4),
(50, 'Accounting', 102, 5),
(60, 'HR', 103, 6),
(70, 'Public Relations', 104, 7);

INSERT INTO LOCA (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES
(3, '789 Elm St', 54321, 'Chicago', 'IL', 1),
(4, '101 Oak St', 98765, 'Houston', 'TX', 2),
(5, '555 Maple Ave', 12345, 'San Francisco', 'CA', 1),
(6, '888 Pine St', 67890, 'Seattle', 'WA', 2),
(7, '222 Walnut St', 13579, 'Boston', 'MA', 1);



-- Question 1

SELECT * FROM EMP 
WHERE EMPLOYEE_ID IN (134, 159, 183);


SELECT * FROM EMP
WHERE DEPARTMENT_ID NOT IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM EMP
    WHERE MANAGER_ID BETWEEN 100 AND 200
);

SELECT *
FROM EMP
WHERE COMMISSION_PCT  = (
    SELECT MAX(COMMISSION_PCT)
    FROM EMP
    WHERE COMMISSION_PCT NOT IN (
        SELECT MAX(COMMISSION_PCT) FROM EMP
    )
);

SELECT * FROM EMP
WHERE COMMISSION_PCT = (
    SELECT MIN(COMMISSION_PCT)
    FROM EMP
    WHERE COMMISSION_PCT NOT IN (
        SELECT MIN(COMMISSION_PCT) FROM EMP
    )
);

SELECT * FROM EMP e1
WHERE (
    SELECT COUNT(DISTINCT e2.COMMISSION_PCT)
    FROM EMP e2
    WHERE e1.COMMISSION_PCT > e2.COMMISSION_PCT
) = 1;


SELECT DISTINCT DEPARTMENT_ID
FROM EMP
WHERE DEPARTMENT_ID IS NOT NULL;


SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM EMP e1
WHERE EXISTS (
    SELECT 1
    FROM EMP e2
    WHERE e2.COMMISSION_PCT > 0.11
    AND e1.DEPARTMENT_ID = e2.DEPARTMENT_ID
);

SELECT d.DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM DEPT d 
WHERE NOT EXISTS (
    SELECT 1
    FROM EMP e
    WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
);


SELECT FIRST_NAME, LAST_NAME
FROM EMP e1
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM EMP e2
    WHERE e2.FIRST_NAME LIKE '%a%' OR  e2.LAST_NAME LIKE '%a%'
);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, COMMISSION_PCT
FROM EMP e1
WHERE COMMISSION_PCT > (
    SELECT AVG(COMMISSION_PCT)
    FROM EMP
)
AND EXISTS (
    SELECT 1
    FROM EMP e2
    WHERE e1.DEPARTMENT_ID = e2.DEPARTMENT_ID
    AND (e2.FIRST_NAME LIKE '%J%' OR e2.LAST_NAME LIKE '%J%')
);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID
FROM EMP
WHERE COMMISSION_PCT > ANY (
    SELECT COMMISSION_PCT
    FROM EMP
    WHERE JOB_ID = 'IT_PROG'
);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID
FROM EMP
WHERE COMMISSION_PCT > ALL (
    SELECT COMMISSION_PCT
    FROM EMP
    WHERE JOB_ID = 'IT_PROG'
) AND JOB_ID <> 'IT_PROG';

SELECT FIRST_NAME, LAST_NAME, COMMISSION_PCT, DEPARTMENT_ID
FROM EMP
WHERE COMMISSION_PCT > (
    SELECT AVG(COMMISSION_PCT)
    FROM EMP
)
ORDER BY COMMISSION_PCT DESC;


SELECT *
FROM EMP
WHERE COMMISSION_PCT BETWEEN (
    SELECT MIN(COMMISSION_PCT)
    FROM EMP
) AND 2500;
